# Generated by Django 5.0.5 on 2024-05-11 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='created_by',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='pub_date',
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(max_length=100),
        ),
    ]
